(ns halite.constants)

(def charge-count 9)
(def infinity 500000)
(def weighted-enemy-vs-neutral 20)
(def early-num-future-rounds 4)
(def late-num-future-rounds 2)
(def penalty-for-targeting-unowned-cell 500)
(def num-to-join-up-early 3)
(def num-to-join-up 7)
(def distance-join-up 50)
(def distance-to-avoid-neutral-cells 5)
(def distance-to-prepare-for-attack 5)
(def attack-strength 33)
(def rounds-of-production-still 4)
(def per-player-strength 7)
(def modifier-multiple 1)
(def site-worth-taking-profit 25)
(def num-targets-to-track 38)
(def max-early-round-targets 20)
(def charge-count 13)
(def max-distance-to-move 25)
