name: Build Halite Bots

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  run-match:
    name: Run Match
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        bot:
          - easy
          - intermediate
          - hard
          - nightmare
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.bot }}bot
          tags: |
            type=sha
            type=raw,value={{date 'YYYYMMDD-HHmmss'}}
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build with gradle
        working-directory: docker/${{ matrix.bot }}
        run: ./gradlew installDist --no-daemon
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: docker/${{ matrix.bot }}/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
