name: Build Halite Bots

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io

jobs:
  build-bots:
    name: Build Bots
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        bot:
          - novicebot
          - easybot
          - intermediatebot
          - hardbot
          - nightmarebot
          - mzotkiew
          - erdman_v12
          - erdman_v17
          - erdman_v26
          - djma
          - shummie  # currently broken due to numpy issues
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.bot }}
          tags: |
            type=raw,value={{date 'YYYYMMDD-HHmmss'}}
            type=sha
      - uses: extractions/setup-just@v1
      - name: Build
        working-directory: docker/${{ matrix.bot }}
        run: if [[ -e justfile ]]; then just; fi
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: docker/${{ matrix.bot }}/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
